networks:
  backend:

volumes:
  pgdata:
  appdata:
  csvdata:

services:
  db:
    image: postgres:16
    container_name: iss_db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - backend
    ports:
      - "5432:5432"

  rust_iss:
    build:
      context: ./services/rust-iss
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend
    ports:
      - "8081:3000"

  redis:
    image: redis:7.0.12-alpine
    container_name: redis_cache
    networks:
      - backend
    ports:
      - "6379:6379"

  php:
    build:
      context: ./services/php-web
    container_name: php_web
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      rust_iss:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - backend
    volumes:
      - appdata:/var/www/html
      - ./services/php-web/laravel-patches:/opt/laravel-patches:ro

  nginx:
    image: nginx:1.27-alpine
    container_name: web_nginx
    depends_on:
      - php
    volumes:
      - appdata:/var/www/html:ro
      - ./services/php-web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
    ports:
      - "8080:80"

  js-legacy:
    build:
      context: ./services/js-legacy
    container_name: js_legacy
    env_file: .env
    environment:
      CSV_OUT_DIR: ${CSV_OUT_DIR}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      GEN_PERIOD_SEC: ${GEN_PERIOD_SEC:-300}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - csvdata:/data/csv
    networks:
      - backend
